### PR TITLE
.env  N8N_BASIC_AUTH_ACTIVE=false

### PR DESCRIPTION
**Pull request by rubensflinco**
I believe it's best to disable this authentication since n8n has a registration system outside that YunoHost itself already has the user system, this option confuses people more and generates several reports both on the forum and on github.

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rubensflinco** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by Limezy** [comment]
Can we merge ?
Or shall it be a "if" testing if install is on `/` or not ?

**Comment by ecossistemadev** [comment]
up

**Pull request closed without merging**
