### PR TITLE
Implement WEBHOOK_URL in environment file

### LINKED ISSUE #10: OAuth Redirect Urls point to localhost and port instead of domain
### Describe the bug

Can't set the WEBHOOK_URL and it defaults to localhost which causes OAuth redirect urls to not work. I have tried setting the Environement variables on the server hosting Yunohost as well as defining the variables in the settings file. 

### Context

- Hardware: VPS on Vultr
- YunoHost version: 4.3.3 Stable
- I have access to my server: SSH and Web Admin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no
- Using, or trying to install package version/branch: Master

### Steps to reproduce

- Install like normal
- Attempt to add Box node
- Oath credential redirect url will be localhost

### Expected behavior

* webhook_url would be set the same as host.

### PR DESCRIPTION
**Pull request by tituspijean**
Closes #10 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
@brimwats could you try upgrading to that code and see if it works as intended?

`yunohost app upgrade n8n -u https://github.com/YunoHost-Apps/n8n_ynh/tree/webhook_url --force`

🤞

**Comment by brimwats** [comment]
I can this weekend!  will this override my current .env file?

**Comment by tituspijean** [comment]
Yes indeed

**Comment by fflorent** [comment]
LGTM, I'll try the patch this weekend :)

**Comment by brimwats** [comment]
@tituspijean it works! Also didn't even erase my old data, nice job

**Review by fflorent — APPROVED** [review]

**Comment by brimwats** [comment]
Will I have to do anything to revert to the main branch?

**Comment by tituspijean** [comment]
@brimwats no, the YunoHost core only monitors the branch advertised in the catalog (`master` by default). So whenever a newer version is released on that branch you will get the upgrade to it.

**Pull request merged**
