### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
-  I would like to install n8n in a subpath instead of a full-domain;
-  Also don't enable https in n8n runtime (useless because of nginx);
-  Remove useless (?) variables;
-  Upgrading the app doesn't update the .env file;

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by fflorent** [comment]
Hi @ericgaspar 
Shall I merge the PR or would you have other things to bring here?
Thanks! :pray:

**Comment by ericgaspar** [comment]
Let's meeerge! As maintainer you can fill your name in the manifest.
As for the license issue, I have no clear idea of what needs to be done.

**Comment by fflorent** [comment]
>  As for the license issue, I have no clear idea of what needs to be done.

I changed `Apache-2.0` for `Apache-2.0-with-commons-clause` even if that's not standard :shrug:

**Pull request merged**
