### PR TITLE
Update .env

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
@fflorent an env variable was missing... to be tested

**Comment by fflorent** [comment]
I test that. 

I wonder if there are ways to migrate data from sqlite to mariadb

**Comment by fflorent** [comment]
Might be a good start (in french and not tested at this point):
https://blog.bandinelli.net/index.php?post/2014/03/27/sqlite3-to-mysql

**Comment by fflorent** [comment]
I get this error:

> mars 29 14:45:26 zeteo.me systemd[1]: Started n8n: Workflow Automation Tool.
> mars 29 14:45:31 zeteo.me n8n[14480]: Initializing n8n process
> mars 29 14:45:31 zeteo.me n8n[14480]: **There was an error initializing DB: "The file "localhost" could not be found."**
> mars 29 14:45:31 zeteo.me n8n[14480]: Stopping n8n...
> mars 29 14:45:31 zeteo.me systemd[1]: n8n.service: Main process exited, code=exited, status=1/FAILURE
> mars 29 14:45:31 zeteo.me systemd[1]: n8n.service: Failed with result 'exit-code'.

**Comment by ericgaspar** [comment]
not really surprising according to the creative var maming 😅

**Comment by fflorent** [comment]
Much better :100: 

I attempt add a migration from sqlite to mariadb to the upgrade script.

**Comment by fflorent** [comment]
The above script does not help much.

I tried this one: https://github.com/techouse/sqlite3-to-mysql

It's promising, but still have an issue:
```
2022-03-29 15:41:12 ERROR    MySQL failed creating table credentials_entity: 1901 (HY000): Function or expression '`STRFTIME`()' cannot be used in the DEFAULT clause of `createdAt`
1901 (HY000): Function or expression '`STRFTIME`()' cannot be used in the DEFAULT clause of `createdAt
```

I miss time for continuing working on it today. I try to keep you informed.

**Comment by fflorent** [comment]
!testme

**Review by tituspijean — APPROVED** [review]

**Pull request merged**
