### PR TITLE
Bump to version 1.29 of n8n

### PR DESCRIPTION
**Pull request by clawfire**
## Problem

- The available version is 14 releases behind

## Solution

- Bump version to the latest stable

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by clawfire** [comment]
!testme

**Comment by CodeShakingSheep** [comment]
Hi @clawfire,
Actually you need to increase the n8n version in `_common` as it's read from there during install. And also please change the base branch to testing. Thanks for your contribution.

**Comment by clawfire** [comment]
> Actually you need to increase the n8n version in `_common.sh` as it's read from there during install.

That's what I did. I think?

> please change the base branch to testing.

I'll do that right away

**Comment by CodeShakingSheep** [comment]
> > Actually you need to increase the n8n version in `_common.sh` as it's read from there during install.
> 
> That's what I did. I think?
> 
Oh yes, you're right. Somehow I only saw your change in `manifest.toml`. 😄 It's good.

**Comment by CodeShakingSheep** [comment]
!testme

**Pull request merged**
